// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMrW8SZf77_ZnLHuBCpSPOEd_ZlRpHbmA',
    appId: '1:296048475723:web:5c260e21b5e570bf0fd7ce',
    messagingSenderId: '296048475723',
    projectId: 'chatbox-1cbb4',
    authDomain: 'chatbox-1cbb4.firebaseapp.com',
    storageBucket: 'chatbox-1cbb4.appspot.com',
    measurementId: 'G-3Z8WWNXJKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYARhHtLd1vprimMfVnytZlpHmOVu37ps',
    appId: '1:296048475723:android:68a173d428f31eab0fd7ce',
    messagingSenderId: '296048475723',
    projectId: 'chatbox-1cbb4',
    storageBucket: 'chatbox-1cbb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJYKi9alHgm5H8hyDVIx38Ke7h8qYLHmc',
    appId: '1:296048475723:ios:15e75bfd8d699f7d0fd7ce',
    messagingSenderId: '296048475723',
    projectId: 'chatbox-1cbb4',
    storageBucket: 'chatbox-1cbb4.appspot.com',
    iosClientId: '296048475723-mg16k3kqo67ahafmusu0mh04vou57q1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJYKi9alHgm5H8hyDVIx38Ke7h8qYLHmc',
    appId: '1:296048475723:ios:15e75bfd8d699f7d0fd7ce',
    messagingSenderId: '296048475723',
    projectId: 'chatbox-1cbb4',
    storageBucket: 'chatbox-1cbb4.appspot.com',
    iosClientId: '296048475723-mg16k3kqo67ahafmusu0mh04vou57q1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbot',
  );
}
